import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings.development')
django.setup()

from django.db import connection

with connection.cursor() as cursor:
    print("Dropping wishlist_wishlistitem table...")
    cursor.execute("DROP TABLE IF EXISTS wishlist_wishlistitem CASCADE;")
    
    print("Recreating table with product_id...")
    cursor.execute("""
        CREATE TABLE wishlist_wishlistitem (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            added_at timestamp with time zone NOT NULL,
            product_id bigint NOT NULL REFERENCES products_product(id) DEFERRABLE INITIALLY DEFERRED,
            wishlist_id bigint NOT NULL REFERENCES wishlist_wishlist(id) DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT wishlist_wishlistitem_wishlist_id_product_id_key UNIQUE (wishlist_id, product_id)
        );
    """)
    cursor.execute("CREATE INDEX wishlist_wishlistitem_product_id_idx ON wishlist_wishlistitem (product_id);")
    cursor.execute("CREATE INDEX wishlist_wishlistitem_wishlist_id_idx ON wishlist_wishlistitem (wishlist_id);")

print("Successfully reverted wishlist_wishlistitem table!")
